Repository TeamDon-tBe/SERVER, pull requests merged in 2024-02, with the labels that each got.

#121 [FIX] 게시물에 해당하는 답글 순서 변경 #120
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/comment/repository/CommentRepository.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/comment/service/CommentQueryService.java
Labels: 🐰보람🐰, 🔨 FIX 🔨

#126 [REFACTOR]MemberService와 GhostService분리작업 완료
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/ghost/controller/GhostController.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/ghost/service/GhostCommandService.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/member/controller/MemberController.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/member/dto/request/MemberNicknameCheckRequestDto.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/member/service/Impl/MemberServiceImpl.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/member/service/MemberCommandService.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/member/service/MemberQueryService.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/member/service/MemberService.java
Labels: 🐮홍준🐮, ♻️ REFACTOR ♻️ 

#128 [FEAT]500에러와 토큰 관련 에러 슬랙 알림 기능 추가
  DontBeServer/build.gradle
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/HealthCheckController.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/comment/service/CommentCommendService.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/common/advice/ControllerExceptionAdvice.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/common/config/jwt/JwtTokenProvider.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/common/response/ApiResponse.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/common/response/ErrorStatus.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/common/util/SlackUtil.java
Labels: 🐮홍준🐮, ✨ FEAT ✨

#129 [Refactor] 전체조회 api cursor기반 페이지네이션 적용 /#125
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/comment/controller/CommentController.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/comment/repository/CommentRepository.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/comment/service/CommentQueryService.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/content/controller/ContentController.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/content/repository/ContentRepository.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/content/service/ContentQueryService.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/notification/controller/NotificationController.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/notification/repository/NotificationRepository.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/notification/service/NotificationQueryService.java
Labels: 🐰보람🐰, ♻️ REFACTOR ♻️ 

#134 [REFACTOR]기존에 사용하던 닉네임 그대로 사용할 수 있게 중복 검사 로직 수정
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/member/controller/MemberController.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/member/service/MemberQueryService.java
Labels: 🐮홍준🐮, ♻️ REFACTOR ♻️ 

#137 [FEAT]애플 소셜 로그인 구현
  DontBeServer/build.gradle
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/auth/SocialPlatform.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/auth/dto/request/AuthRequestDto.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/auth/service/AppleAuthService.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/auth/service/Impl/AuthServiceImpl.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/common/response/ErrorStatus.java
Labels: 🐮홍준🐮, ✨ FEAT ✨

#139 [FEAT]투명도 V2 기능 구현
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/ghost/controller/GhostController.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/ghost/domain/Ghost.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/ghost/dto/request/GhostClickRequestDto.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/ghost/service/GhostCommandService.java
Labels: 🐮홍준🐮, ✨ FEAT ✨

#141 [FIX]프로필 수정 시에 isFcmAllowed이 false로 수정되는 에러 수정
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/member/dto/request/MemberProfilePatchRequestDto.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/member/service/MemberCommandService.java
Labels: 🐮홍준🐮, 🔨 FIX 🔨

#142 [REFACTOR] 게시글 softdelete 적용 #132
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/content/domain/Content.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/content/repository/ContentRepository.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/content/service/ContentCommandService.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/content/service/ExpiredContentDeleteBatch.java
Labels: 🐰보람🐰, ♻️ REFACTOR ♻️ 

#146 [FEAT]앱 심사용 탈퇴하기 로직 추가
  DontBeServer/.DS_Store
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/content/service/ContentCommandService.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/member/service/MemberCommandService.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/notification/repository/NotificationRepository.java
Labels: 🐮홍준🐮, ✨ FEAT ✨

#151 [feat] 실제 사용될 계정 삭제 api 구현
  DontBeServer/.DS_Store
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/auth/SocialPlatform.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/auth/service/Impl/AuthServiceImpl.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/content/repository/ContentLikedRepository.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/content/repository/ContentRepository.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/content/service/ContentCommandService.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/ghost/domain/Ghost.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/ghost/repository/GhostRepository.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/ghost/service/ExpiredGhostDeleteBatch.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/ghost/service/GhostCommandService.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/ghost/service/GhostQueryService.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/member/controller/MemberController.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/member/domain/Member.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/member/dto/request/MemberWithdrawRequestDto.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/member/repository/MemberRepository.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/member/service/ExpiredMemberDeleteBatch.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/member/service/MemberCommandService.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/notification/repository/NotificationRepository.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/common/response/ErrorStatus.java
Labels: 🐰보람🐰, ✨ FEAT ✨

#155 [FIX] 게시글 삭제 시 해당 게시글에 달린 답글의 commentGhost 노티 삭제되도록 수정
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/content/service/ContentCommandService.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/ghost/service/GhostCommandService.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/member/service/MemberCommandService.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/notification/service/NotificationQueryService.java
Labels: 🐰보람🐰, 🔨 FIX 🔨

#159 [FEAT]프로필 이미지 변경 기능 추가
  DontBeServer/build.gradle
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/auth/service/Impl/AuthServiceImpl.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/member/controller/MemberController.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/member/dto/request/ProfilePatchRequestDto.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/member/service/MemberCommandService.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/common/response/ErrorStatus.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/external/s3/config/AWSConfig.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/external/s3/service/S3Service.java
Labels: 🐮홍준🐮, ✨ FEAT ✨

#161 [FIX]멀티파트 관련 octet-stream에러 converter생성을 통해 해결
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/common/converter/MultipartJackson2HttpMessageConverter.java
Labels: 🐮홍준🐮, 🔨 FIX 🔨

#163 [FIX] soft delete와 앱 심사용 탈퇴하기 api 충돌 해결
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/comment/service/CommentCommendService.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/content/service/ContentCommandService.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/common/converter/MultipartJackson2HttpMessageConverter.java
Labels: 🐰보람🐰, 🔨 FIX 🔨

#165 [FIX]octet-stream에러 관련 converter복구
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/common/converter/MultipartJackson2HttpMessageConverter.java
Labels: 🐮홍준🐮, 🔨 FIX 🔨

#169 [FIX] 계정삭제 api 메소드 변경
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/member/controller/MemberController.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/member/dto/request/MemberWithdrawRequestDto.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/member/dto/request/MemberWithdrawalPatchRequestDto.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/member/service/MemberCommandService.java
Labels: 🐰보람🐰, 🔨 FIX 🔨

#173 [fix] response에 notificationId 추가
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/notification/dto/response/NotificationAllResponseDtoVer2.java
Labels: 🐰보람🐰, 🔨 FIX 🔨
