Repository TeamDon-tBe/SERVER, pull requests merged in 2024-05, with the labels that each got.

#195 [FEAT]Dockerfile Dev,Pord분리 및 생성
  DontBeServer/Dockerfile-Dev
  DontBeServer/Dockerfile-Prod
Labels: 🐮홍준🐮, 🐰보람🐰, ✨ FEAT ✨

#197 [FIX]actuator/health만 허용되도록 securityConfig수정
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/common/config/SecurityConfig.java
Labels: 🐮홍준🐮, 🔨 FIX 🔨

#199 [FEAT] actingContinue노티 발생 로직 추가
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/notification/service/NotificationQueryService.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/common/crontab/GhostScheduler.java
Labels: 🐮홍준🐮, ✨ FEAT ✨

#201 [FIX]ghostNotification관련 보안 강화
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/ghost/service/GhostCommandService.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/notification/service/NotificationQueryService.java
Labels: 🐮홍준🐮, 🐰보람🐰, 🔨 FIX 🔨

#203 [FEAT] 사진첨부 기능이 추가된 게시글 작성 api구현
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/content/controller/ContentController.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/content/domain/Content.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/content/service/ContentCommandService.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/external/s3/service/S3Service.java
Labels: 🐰보람🐰, ✨ FEAT ✨

#205 [FEAT] 게시글 조회 시 response에 이미지 추가
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/content/controller/ContentController.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/content/dto/response/ContentGetAllByMemberResponseDtoVer2.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/content/dto/response/ContentGetAllResponseDtoVer3.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/content/dto/response/ContentGetDetailsResponseDtoVer3.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/content/service/ContentQueryService.java
Labels: 🐰보람🐰, ✨ FEAT ✨

#207 [FEAT]인기글 관련 노티 발생 기능 구현
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/content/repository/ContentRepository.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/member/repository/MemberRepository.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/common/crontab/PopularContentScheduler.java
Labels: 🐮홍준🐮, ✨ FEAT ✨

#210 [FEAT]사진첨부 기능이 추가된 답글 작성 api구현
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/comment/controller/CommentController.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/comment/domain/Comment.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/comment/service/CommentCommendService.java
Labels: 🐰보람🐰, ✨ FEAT ✨

#214 [FIX] 프로필 이미지 수정 시에 기본 이미지가 삭제되는 로직 수정
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/member/service/MemberCommandService.java
Labels: 🐮홍준🐮, 🔨 FIX 🔨

#216 [FEAT] Fcm 푸시 알림 서비스 구현
  DontBeServer/.gitignore
  DontBeServer/build.gradle
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/auth/dto/response/AuthResponseDto.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/auth/service/Impl/AuthServiceImpl.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/comment/service/CommentCommendService.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/content/service/ContentCommandService.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/member/domain/Member.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/member/dto/request/ProfilePatchRequestDto.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/member/service/MemberCommandService.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/common/crontab/PopularContentScheduler.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/common/response/ErrorStatus.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/external/fcm/dto/FcmMessageDto.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/external/fcm/service/FcmService.java
Labels: 🐮홍준🐮, ✨ FEAT ✨

#218 [FIX]fire-base경로 문제로 코드 수정
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/external/fcm/service/FcmService.java
Labels: 🐮홍준🐮, 🔨 FIX 🔨

#220 [FIX] EC2환경에서 fire-base.json매칭 못하는 이슈 해결
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/external/fcm/service/FcmService.java
Labels: 🐮홍준🐮, 🔨 FIX 🔨

#222 [FIX] ec2 firebase경로 수정
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/external/fcm/service/FcmService.java
Labels: 🐮홍준🐮, 🔨 FIX 🔨

#224 [FIX]fire-base.json파일 불러오는 방식 수정
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/external/fcm/service/FcmService.java
Labels: 🐮홍준🐮, 🔨 FIX 🔨

#226 [FIX] fire-base.json경로 관련 롤백
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/external/fcm/service/FcmService.java
Labels: 🐮홍준🐮, 🔨 FIX 🔨

#230 [FIX]isPushAlarmAllowed관련 null이슈 해결
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/auth/service/Impl/AuthServiceImpl.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/comment/service/CommentCommendService.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/content/service/ContentCommandService.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/member/domain/Member.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/common/crontab/PopularContentScheduler.java
Labels: 🐮홍준🐮, 🔨 FIX 🔨

#234 [FIX]테스트를 위해 로직 수정
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/content/service/ContentCommandService.java
Labels: 🐮홍준🐮, 🔨 FIX 🔨

#236 [FIX]json파일 출력 추가 테스트용
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/external/fcm/service/FcmService.java
Labels: 🐮홍준🐮, 🔨 FIX 🔨

#238 [FEAT]json관련 처리 기능 추가
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/external/fcm/service/FcmService.java
Labels: 🐮홍준🐮, ✨ FEAT ✨

#240 [FIX]FCM관련 테스트용 코드들 삭제
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/content/service/ContentCommandService.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/external/fcm/service/FcmService.java
Labels: 🐮홍준🐮, 🔨 FIX 🔨

#242 [FIX] 답글 관련 푸시알림 바디값 수정
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/comment/service/CommentCommendService.java
Labels: 🐮홍준🐮, 🔨 FIX 🔨
