Repository TeamDon-tBe/SERVER, pull requests merged in 2024-01, with the labels that each got.

#4 [FIX]gitignore수정
  .DS_Store
  DontBeServer/.DS_Store
  DontBeServer/.gitignore
  DontBeServer/Dockerfile
Labels: 🐮홍준🐮, 🐰보람🐰, ⚙️ SETTING ⚙️

#6 [FEAT]카카오 소셜 로그인과 스프링 시큐리티 구현 완료
  DontBeServer/.gitignore
  DontBeServer/build.gradle
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/HealthCheckController.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/member/auth/SocialPlatform.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/member/auth/controller/AuthController.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/member/auth/dto/SocialInfoDto.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/member/auth/dto/request/AuthRequestDto.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/member/auth/dto/response/AuthResponseDto.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/member/auth/dto/response/AuthTokenResponseDto.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/member/auth/service/AuthService.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/member/auth/service/Impl/AuthServiceImpl.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/member/auth/service/KakaoAuthService.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/member/domain/Member.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/member/repository/MemberRepository.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/common/config/jwt/JwtAuthenticationEntryPoint.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/common/config/jwt/JwtAuthenticationFilter.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/common/config/jwt/JwtExceptionType.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/common/config/jwt/JwtTokenProvider.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/common/config/jwt/UserAuthentication.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/common/util/MemberUtil.java
Labels: 🐮홍준🐮, 🐰보람🐰, ✨ FEAT ✨

#8 [SETTING]엔티티 설계 및 프로젝트 구조 수정
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/auth/SocialPlatform.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/auth/controller/AuthController.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/auth/dto/SocialInfoDto.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/auth/dto/request/AuthRequestDto.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/auth/dto/response/AuthResponseDto.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/auth/dto/response/AuthTokenResponseDto.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/auth/service/AuthService.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/auth/service/Impl/AuthServiceImpl.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/auth/service/KakaoAuthService.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/comment/domain/Comment.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/comment/domain/CommentLiked.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/content/domain/Content.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/content/domain/ContentLiked.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/ghost/domain/Ghost.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/ghost/domain/GhostCommandService.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/ghost/domain/GhostQueryService.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/member/auth/SocialPlatform.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/member/controller/MemberController.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/member/domain/Member.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/member/repository/MemberRepository.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/member/service/Impl/MemberServiceImpl.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/member/service/MemberService.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/notification/domain/Notification.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/report/domain/Report.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/common/response/SuccessStatus.java
Labels: 🐮홍준🐮, 🐰보람🐰, ⚙️ SETTING ⚙️

#11 [FEAT]게시물 작성 API개발 완료
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/auth/controller/AuthController.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/comment/domain/Comment.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/comment/domain/CommentLiked.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/content/controller/ContentController.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/content/domain/Content.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/content/domain/ContentLiked.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/content/dto/request/ContentPostRequestDto.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/content/repository/ContentRepository.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/content/service/ContentQueryService.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/member/controller/MemberController.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/common/config/jwt/JwtAuthenticationFilter.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/common/response/ApiResponse.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/common/response/SuccessStatus.java
Labels: 🐮홍준🐮, ✨ FEAT ✨

#13 [FEAT]게시글 삭제 API개발
  DontBeServer/.gitignore
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/content/controller/ContentController.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/content/service/ContentCommandService.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/common/response/ErrorStatus.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/common/response/SuccessStatus.java
Labels: 🐮홍준🐮, ✨ FEAT ✨

#15 [FEAT]답글 작성 API개발 완료 #10
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/auth/controller/AuthController.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/auth/dto/request/AuthRequestDto.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/comment/controller/CommentController.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/comment/dto/request/CommentPostRequestDto.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/comment/repository/CommentRepository.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/comment/service/CommentCommendService.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/content/repository/ContentRepository.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/member/controller/MemberController.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/common/response/ApiResponse.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/common/response/ErrorStatus.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/common/response/SuccessStatus.java
Labels: 🐰보람🐰, ✨ FEAT ✨

#17 [FEAT]답글 삭제하기 API개발완료 #16
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/comment/controller/CommentController.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/comment/domain/Comment.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/comment/repository/CommentRepository.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/comment/service/CommentCommendService.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/content/dto/request/ContentPostRequestDto.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/common/response/ErrorStatus.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/common/response/SuccessStatus.java
Labels: 🐰보람🐰, ✨ FEAT ✨

#21 [FEAT]게시물 상세 조회 API개발
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/comment/repository/CommentRepository.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/content/controller/ContentController.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/content/domain/Content.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/content/dto/response/ContentGetDetailsResponseDto.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/content/repository/ContentLikedRepository.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/content/service/ContentQueryService.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/ghost/repository/GhostRepository.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/ghost/service/GhostCommandService.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/ghost/service/GhostQueryService.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/common/response/SuccessStatus.java
Labels: 🐮홍준🐮, ✨ FEAT ✨

#25 [FEAT]게시물 좋아요 취소 API
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/comment/controller/CommentController.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/content/controller/ContentController.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/content/repository/ContentLikedRepository.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/content/service/ContentCommandService.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/content/service/ContentQueryService.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/notification/repository/NotificationRepository.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/common/response/ErrorStatus.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/common/response/SuccessStatus.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/common/util/TimeUtilCustom.java
Labels: 🐮홍준🐮, ✨ FEAT ✨

#29 [FEAT]유저 프로필 조회API개발
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/member/controller/MemberController.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/member/domain/Member.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/member/dto/response/MemberDetailGetResponseDto.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/member/dto/response/MemberGetProfileResponseDto.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/member/service/Impl/MemberServiceImpl.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/member/service/MemberService.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/common/response/SuccessStatus.java
Labels: 🐮홍준🐮, ✨ FEAT ✨

#31 [REFACTOR]멤버 전체 투명도 정제 처리 추가
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/content/dto/response/ContentGetDetailsResponseDto.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/content/service/ContentQueryService.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/member/dto/response/MemberGetProfileResponseDto.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/member/service/Impl/MemberServiceImpl.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/common/response/ErrorStatus.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/common/util/GhostUtil.java
Labels: 🐮홍준🐮, ✨ FEAT ✨

#34 [FEAT]투명도 낮추기 API개발
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/ghost/domain/Ghost.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/ghost/repository/GhostRepository.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/member/controller/MemberController.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/member/domain/Member.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/member/dto/request/MemberClickGhostRequestDto.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/member/service/Impl/MemberServiceImpl.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/member/service/MemberService.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/common/response/ErrorStatus.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/common/response/SuccessStatus.java
Labels: 🐮홍준🐮, ✨ FEAT ✨

#36 [FEAT] 답글 좋아요 API 기능 구현 #32
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/comment/controller/CommentController.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/comment/domain/CommentLiked.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/comment/dto/request/CommentLikedRequestDto.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/comment/repository/CommentLikedRepository.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/comment/service/CommentCommendService.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/content/service/ContentCommandService.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/common/response/ErrorStatus.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/common/response/SuccessStatus.java
Labels: 🐰보람🐰, ✨ FEAT ✨

#38 [FEAT]유저 프로필 수정 API개발
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/member/controller/MemberController.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/member/domain/Member.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/member/dto/request/MemberProfilePatchRequestDto.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/member/service/Impl/MemberServiceImpl.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/member/service/MemberService.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/common/response/SuccessStatus.java
Labels: 🐮홍준🐮, ✨ FEAT ✨

#40 [Feat] 답글 좋아요 취소 API 구현 #37
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/comment/controller/CommentController.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/comment/repository/CommentLikedRepository.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/comment/service/CommentCommendService.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/common/response/ErrorStatus.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/common/response/SuccessStatus.java
Labels: 🐰보람🐰, ✨ FEAT ✨

#41 [FEAT]디비 스케쥴러 구현 완료
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/DontBeServerApplication.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/ghost/domain/Ghost.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/ghost/repository/GhostDbRepository.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/common/crontab/GhostScheduler.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/common/entity/BaseDateEntity.java
Labels: 🐮홍준🐮, ✨ FEAT ✨

#43 [FEAT]게시물 리스트 조회 API 개발
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/content/controller/ContentController.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/content/dto/response/ContentGetAllResponseDto.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/content/service/ContentQueryService.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/common/response/SuccessStatus.java
Labels: 🐮홍준🐮, ✨ FEAT ✨

#45 [FEAT]유저에 해당하는 게시글 조회 API 개발
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/content/controller/ContentController.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/content/dto/response/ContentGetAllByMemberResponseDto.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/content/repository/ContentRepository.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/content/service/ContentQueryService.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/common/response/SuccessStatus.java
Labels: 🐮홍준🐮, ✨ FEAT ✨

#47 [FEAT]닉네임 중복 검사 API 개발
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/member/controller/MemberController.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/member/dto/request/MemberNicknameCheckRequestDto.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/member/repository/MemberRepository.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/member/service/Impl/MemberServiceImpl.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/member/service/MemberService.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/common/response/ErrorStatus.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/common/response/SuccessStatus.java
Labels: 🐮홍준🐮, ✨ FEAT ✨

#49 [FEAT]노티 읽음 처리 API개발 완료
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/notification/controller/NotificationController.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/notification/domain/Notification.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/notification/repository/NotificationRepository.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/notification/service/NotificationCommandService.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/common/response/SuccessStatus.java
Labels: 🐮홍준🐮, ✨ FEAT ✨

#52 [FEAT] 게시글에 해당하는 답글 리스트 조회 #20
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/comment/controller/CommentController.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/comment/dto/response/CommentAllResponseDto.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/comment/repository/CommentLikedRepository.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/comment/repository/CommentRepository.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/comment/service/CommentQueryService.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/common/response/SuccessStatus.java
Labels: 🐰보람🐰, ✨ FEAT ✨

#55 [FIX]디비 스케줄러 실행 시간 수정
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/common/crontab/GhostScheduler.java
Labels: 🐮홍준🐮, ✨ FEAT ✨

#57 [FIX]소셜 로그인을 통해 가져오는 정보 수정 및 계정 정보 조회API수정
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/auth/dto/SocialInfoDto.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/auth/service/Impl/AuthServiceImpl.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/auth/service/KakaoAuthService.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/member/domain/Member.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/member/dto/response/MemberDetailGetResponseDto.java
Labels: 🐮홍준🐮, 🔨 FIX 🔨

#58 멤버에 해당하는 답글 리스트 조회 API 구현/#53
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/comment/controller/CommentController.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/comment/dto/request/CommentPostRequestDto.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/comment/dto/response/CommentAllByMemberResponseDto.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/comment/repository/CommentRepository.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/comment/service/CommentCommendService.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/comment/service/CommentQueryService.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/common/response/SuccessStatus.java
Labels: 🐰보람🐰, 🔨 FIX 🔨, ✨ FEAT ✨

#61 [FIX]노티 체크 API메서드 수정
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/notification/controller/NotificationController.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/common/response/SuccessStatus.java
Labels: 🐮홍준🐮, 🔨 FIX 🔨

#64 [FIX] 소셜로그인 API 호출 시 default닉네임 ""으로 변경 #63
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/auth/service/Impl/AuthServiceImpl.java
Labels: 🐰보람🐰, 🔨 FIX 🔨

#62 [FEAT] 멤버에 해당하는 노티 리스트 조회 API 구현 완료 #59
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/comment/repository/CommentRepository.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/notification/controller/NotificationController.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/notification/dto/response/NotificationAllResponseDto.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/notification/repository/NotificationRepository.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/notification/service/NotificationQueryService.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/common/response/SuccessStatus.java
Labels: 🐰보람🐰, ✨ FEAT ✨

#66 [FEAT]소셜 닉네임 받아서 저장하기
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/auth/service/Impl/AuthServiceImpl.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/member/domain/Member.java
Labels: 🐮홍준🐮, ✨ FEAT ✨

#69 [FIX]각종 이슈 해결
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/comment/domain/Comment.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/comment/repository/CommentRepository.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/comment/service/CommentQueryService.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/content/domain/Content.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/content/repository/ContentRepository.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/content/service/ContentQueryService.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/member/controller/MemberController.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/member/service/Impl/MemberServiceImpl.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/member/service/MemberService.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/notification/repository/NotificationRepository.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/notification/service/NotificationQueryService.java
Labels: 🐮홍준🐮, 🔨 FIX 🔨

#72 [FIX]노티피케이션 전체 조회 로직 수정
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/notification/service/NotificationQueryService.java
Labels: 🐮홍준🐮, 🔨 FIX 🔨

#74 [FIX]토큰 이외에 401에러 없게 수정
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/comment/service/CommentCommendService.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/content/service/ContentCommandService.java
Labels: 🐮홍준🐮, 🔨 FIX 🔨

#76 게시물에 해당하는 답글 리스트 조회 API 페이지네이션 구현 /#70
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/comment/controller/CommentController.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/comment/repository/CommentRepository.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/comment/service/CommentQueryService.java
Labels: 🐰보람🐰, ADD

#78 [ADD] 커서기반 pagination 적용 - 유저에 해당하는 답글 리스트 조회 API #77
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/comment/controller/CommentController.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/comment/repository/CommentRepository.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/comment/service/CommentQueryService.java
Labels: 🐰보람🐰, ADD

#80 [FEAT]투명도 클릭시 -85가 되면 제한 노티 생성 + 노티 리스트 조회 로직 수정
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/member/service/Impl/MemberServiceImpl.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/notification/dto/response/NotificationAllResponseDto.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/notification/service/NotificationQueryService.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/common/response/ErrorStatus.java
Labels: 🐮홍준🐮, ✨ FEAT ✨

#85 [FEAT]스웨거 적용
  .DS_Store
  DontBeServer/build.gradle
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/HealthCheckController.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/auth/controller/AuthController.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/comment/controller/CommentController.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/content/controller/ContentController.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/member/controller/MemberController.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/notification/controller/NotificationController.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/common/config/SwaggerConfig.java
Labels: 🐮홍준🐮, ✨ FEAT ✨

#87 [FIX] 멤버에 해당하는 게시글 조회 에러 수정 #86
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/comment/controller/CommentController.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/content/controller/ContentController.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/content/service/ContentQueryService.java
Labels: bug, 🐰보람🐰, 🔨 FIX 🔨

#88 [FIX] 멤버에 해당하는 게시글 조회 에러 수정 #86
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/content/controller/ContentController.java
Labels: bug, 🐰보람🐰

#91 Fix dto관련 및 답글 작성 시 노티 발생 하도록 수정/#89
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/comment/dto/request/CommentPostRequestDto.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/comment/dto/response/CommentAllResponseDto.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/comment/service/CommentCommendService.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/comment/service/CommentQueryService.java
Labels: 🐰보람🐰, 🔨 FIX 🔨

#92 [FEAT]각종 삭제, 취소 관련 노티 동시 삭제
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/comment/repository/CommentLikedRepository.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/comment/repository/CommentRepository.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/comment/service/CommentCommendService.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/content/service/ContentCommandService.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/notification/repository/NotificationRepository.java
Labels: 🐮홍준🐮, ✨ FEAT ✨

#102 [FIX]게시글 전체 조회에서 유저 고스트 정제과정 추가
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/content/dto/response/ContentGetAllResponseDto.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/content/service/ContentQueryService.java
Labels: 🐮홍준🐮, 🔨 FIX 🔨

#104 [FIX]멤버 게시글 조회에서 작성자 ghost정제 과정 추가
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/content/dto/response/ContentGetAllByMemberResponseDto.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/content/service/ContentQueryService.java
Labels: 🐮홍준🐮, 🔨 FIX 🔨

#106 [FIX]답글 작성 시에 생기는 노티 항목 수정
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/comment/service/CommentCommendService.java
Labels: 🐮홍준🐮, 🔨 FIX 🔨

#108 [FIX]답글 삭제 시 투명도 노티 삭제 로직 추가
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/comment/service/CommentCommendService.java
Labels: 🐮홍준🐮, 🔨 FIX 🔨

#110 [FIX]게시글 답글 순서 변경
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/comment/repository/CommentRepository.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/comment/service/CommentQueryService.java
Labels: 🐮홍준🐮, 🔨 FIX 🔨

#112 [FIX]안드 아요 통합 수정
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/comment/service/CommentQueryService.java
Labels: 🐮홍준🐮, 🔨 FIX 🔨

#115 [FIX] commentGhost시 contentId가 반환되므로 게시물 삭제 시 contentId로 검색 후 삭제
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/content/service/ContentCommandService.java
  DontBeServer/src/main/java/com/dontbe/www/DontBeServer/api/member/service/Impl/MemberServiceImpl.java
Labels: 🐰보람🐰, 🔨 FIX 🔨
